import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Inter } from "next/font/google";
import styles from "./globals.module.scss";
import { Footer } from "@/widgets/Footer";
import  { Navigation } from "../widgets/Header/navigation"
import  SearchOrAdd  from "../widgets/SearchOrAdd/SearchOrAdd"
import { PlatformWork } from "@/widgets/PlatformWork";
import { CreateOrderModal } from "@/widgets/CreateOrderModal";
import NewPassword from "@/shared/modals/newPassword/NewPassword";
import VerificationCode from "@/shared/modals/newPassword(code)/VerificationCode";
import LogIn from "@/shared/modals/logIn/LogIn";
import ProductSlider from "@/widgets/ProductSlider/ProductSlider";
import { Company } from "@/widgets/Company/Company";
import ProtectedRoute from "@/features/Login/ProtectedRoute";

const inter = Inter({ weight: ["400", "700","300","500"], subsets: ["latin","cyrillic"] });

const sfPro = localFont({
  src: [
    {
      path: './../shared/assets/font/SFPRODISPLAYREGULAR.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../shared/assets/font/SFPRODISPLAYBLACKITALIC.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './../shared/assets/font/SFPRODISPLAYBOLD.otf',      
      weight: '700',
      style: 'normal',
    },
    {
      path: './../shared/assets/font/SFPRODISPLAYHEAVYITALIC.otf',      
      weight: '700',
      style: 'italic',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sfPro.className} ${styles.body}`}>
        <Navigation />
        {/* <PlatformWork /> */}
        {/* <SearchOrAdd /> */}
        {/* <NewPassword /> */}
        {/* <VerificationCode /> */}
        {/* <LogIn /> */}
        <ProductSlider />
        {children}
        {/* <Comments /> */}
        {/* <OfferCustomer/> */}
        {/* <SimilarOrders/> */}
        {/* <Company /> */}

        {/* <AllOrder/> */}
        
        {/* <SearchProduct /> */}
        {/* <Footer/> */}
        {/* <ProtectedRoute> */}
        {children}
        {/* </ProtectedRoute> */}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
