import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Footer } from "@/widgets/Footer";
import { CommentBlock } from "@/widgets/CommentBlock";
import { Comments } from "@/widgets/Comments";
import { SearchProduct } from "@/widgets/SearchProduct";
import { AllOrder } from "@/widgets/AllOrder";
import { SimilarOrders } from "@/widgets/SimilarOrders";
import { OfferCustomer } from "@/widgets/OfferCustomer";
const roboto = Roboto({
  weight: ["400", "700", "300", "500"],
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        <OfferCustomer/>
        <SimilarOrders/>
        


        <Footer/>

      </body>
    </html>
  );
}
